spring.application.name=fearless-gpus

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/fearless_gpus
spring.datasource.username=fearless_user
spring.datasource.password=fearless_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MinIO
minio.url=http://localhost:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket-name=datasets

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# JWT
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a7589d9c2e428c0b4715f2a1b9c9f28d
jwt.expiration=86400000
